/**
 * Real-account regression probe for the exact noninteractive MCP configuration
 * generated by codex/runner.ts.
 *
 * The first real research run showed every memory_search failing with
 * "MCP tool call requires approval, but approval policy is never", i.e. the
 * entire on-demand recall layer (PROTOCOL §7) was dead in practice.
 *
 *   npx tsx packages/conductor/scripts/probe-mcp-approval.ts
 */
import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { MemoryService } from "../src/memory/service.js";
import { CardStore, FileMemoryBackend } from "../src/memory/cardStore.js";
import { runCodex } from "../src/codex/runner.js";
import {
  MCP_APPROVAL_PROBE_AGENTS,
  MCP_APPROVAL_PROBE_LAUNCH,
} from "../src/prompts/diagnostics.js";

const ENABLED_TOOLS = ["memory_search", "memory_expand"];
const PORT = Number(process.env["PROBE_PORT"] ?? 4795);

async function main(): Promise<void> {
  const root = mkdtempSync(path.join(os.tmpdir(), "mcp-probe-"));
  const cardsDir = path.join(root, "memory", "cards");
  mkdirSync(cardsDir, { recursive: true });
  new CardStore(cardsDir).write({
    id: "M001",
    type: "LEMMA",
    status: "VERIFIED",
    title: "Probe lemma",
    abstract: "A distinctive marker phrase for the probe.",
    content: "The probe marker is BANANAPHONE-7731.",
    tags: ["probe"],
    provenance: "probe fixture",
    sourceArtifact: null,
    dependsOn: [],
  });

  const service = new MemoryService({ port: PORT });
  await service.start();
  const recalls: string[] = [];
  service.registerProject("probe", new FileMemoryBackend(root, (r) => recalls.push(r.op)));
  console.log(`memory service at ${service.url}\n`);

  const token = service.mintToken({ slug: "probe", taskId: "T001", role: "solver", waveId: "W001" });
  const dir = mkdtempSync(path.join(os.tmpdir(), "probe-documented-mcp-"));
  writeFileSync(path.join(dir, "AGENTS.md"), MCP_APPROVAL_PROBE_AGENTS);
  const before = recalls.length;
  const archive = path.join(dir, "codex-events.jsonl");
  const run = await runCodex({
    bin: "codex",
    cwd: dir,
    prompt: MCP_APPROVAL_PROBE_LAUNCH,
    sandbox: "read-only",
    eventsArchiveFile: archive,
    model: "gpt-5.6-luna",
    effort: "low",
    isolatedTask: true,
    mcp: {
      serverName: "memory",
      url: service.url,
      tokenEnvVar: "INVENTIO_TASK_TOKEN",
      token,
      enabledTools: ENABLED_TOOLS,
    },
    wallClockMs: 120_000,
  });
  const out = `${run.lastAgentMessage ?? ""}\n${run.errorDetail ?? ""}\n${readFileSync(archive, "utf8")}`;
  const errMatch = /"message":"([^"]*approval[^"]*)"/i.exec(out);
  const result = {
    called: recalls.length > before,
    sawMarker: out.includes("BANANAPHONE-7731"),
    error: errMatch?.[1] ?? (/"error":\{"message":"([^"]*)"/.exec(out)?.[1] ?? ""),
  };
  service.revokeToken(token);
  console.log(
    `tool-call-reached-server=${result.called} marker=${result.sawMarker} ${result.error.slice(0, 90)}`,
  );

  await service.stop();
  if (!result.called || !result.sawMarker) {
    console.error(`codex status=${run.status} exit=${String(run.exitCode)}`);
    console.error(out.slice(-8_000));
    throw new Error("the documented MCP auto-approval configuration did not reach the server and return the marker");
  }
  console.log("PASS: documented MCP auto-approval reached the authenticated local server");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
