import type { Event } from "@inventio/schema";
import { useStore } from "./store";

/**
 * `?fixture=<name>` replay (UI-SPEC §3): a committed JSON array of events is
 * played into the reducer at 40 events/second with no backend at all. The slot
 * is marked `fixture`, which disables every mutating action in the UI.
 *
 * The JSON files are static assets generated by `scripts/make-fixture.mjs`;
 * schema *test* fixtures are never imported at runtime.
 */

const MODULES = import.meta.glob("../fixtures/*.json", { import: "default" }) as Record<
  string,
  () => Promise<unknown>
>;

const EVENTS_PER_SECOND = 40;

export function fixtureNames(): string[] {
  return Object.keys(MODULES)
    .map((path) => path.replace("../fixtures/", "").replace(/\.json$/, ""))
    .sort();
}

export function hasFixture(name: string): boolean {
  return `../fixtures/${name}.json` in MODULES;
}

export function startFixture(slug: string, name: string): () => void {
  const store = useStore.getState();
  store.resetSlot(slug);
  store.setConnection(slug, "fixture");

  let disposed = false;
  let timer: number | undefined;

  void (async () => {
    const loader = MODULES[`../fixtures/${name}.json`];
    if (!loader) {
      useStore.getState().setSlotError(slug, `no fixture named "${name}"`);
      return;
    }
    let events: Event[];
    try {
      events = (await loader()) as Event[];
    } catch (err) {
      useStore.getState().setSlotError(slug, `fixture load failed: ${String(err)}`);
      return;
    }
    if (disposed) return;

    let index = 0;
    timer = setInterval(() => {
      if (disposed) return;
      const event = events[index];
      index += 1;
      if (event === undefined) {
        if (timer !== undefined) clearInterval(timer);
        timer = undefined;
        return;
      }
      useStore.getState().applyEvents(slug, [event]);
    }, 1000 / EVENTS_PER_SECOND) as unknown as number;
  })();

  return (): void => {
    disposed = true;
    if (timer !== undefined) clearInterval(timer);
  };
}
